using System.Collections;
using System.Collections.Generic;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

[TestFixture]
public class TestNoise : MonoBehaviour
{
    // [Test]
    public void FrameworkForCheck(){
        // Arrange

        // Act

        // Assert
    }

    // public MeshSettings defaultMeshSettings;
    int deafultSize;
    public int defaultMapWidth;
    public int defaultMapHeight;
    public NoiseSettings minimalNoiseSettings;
    public NoiseSettings textureNoiseSettings;
    public NoiseSettings islandNoiseSettings;
    public float minimalMinHeight;
    public float minimalMaxHeight;

    public Vector2 defaultSampleCentre;
	public bool dontDeepenSea = false;
	public bool doDeepenSea = true;
    public float defaultDeepenRatio;

    [OneTimeSetUp]
    public void Init()
    {
        // defaultMeshSettings
        
/*  
        defaultMeshSettings = ScriptableObject.CreateInstance("MeshSettings") as MeshSettings;
        defaultMeshSettings.chunkSizeIndex = 3;
        deafultSize = defaultMeshSettings.numVertsPerLine;
 */        
        // hand crafted, but would be generated by the above!
        // MeshSetting.supportedChunkSizes = {48,72,96,120,144,168,192,216,240};
        // index 3 => 120
        //int chunkSize = 120
        // index 0 => 120
        int chunkSize = 48;
        deafultSize = chunkSize + 5; 
        defaultMapWidth = deafultSize;
        defaultMapHeight = deafultSize;

        // minimalNoiseSettings
        minimalNoiseSettings = new NoiseSettings();
    	minimalNoiseSettings.normalizeMode = Noise.NormalizeMode.Global;
     	minimalNoiseSettings.octaves = 1;
    	minimalNoiseSettings.seed = 0;
    	minimalNoiseSettings.offset = new Vector2(0f, 0f);

        // textureNoiseSettings;
        textureNoiseSettings = new NoiseSettings();
    	textureNoiseSettings.normalizeMode = Noise.NormalizeMode.Global;
     	// leave textureNoiseSettings.octaves at 6
    	textureNoiseSettings.seed = 0;
    	textureNoiseSettings.offset = new Vector2(0f, 0f);

        // islandNoiseSettings;
        islandNoiseSettings = new NoiseSettings();
    	islandNoiseSettings.normalizeMode = Noise.NormalizeMode.Global;
     	// leave textureNoiseSettings.octaves at 6
    	islandNoiseSettings.scale = 2000;
    	islandNoiseSettings.seed = 0;
    	islandNoiseSettings.offset = new Vector2(0f, 0f);

        minimalMinHeight = 0;
        minimalMaxHeight = 1;

        defaultSampleCentre = new Vector2(0f, 0f);
        defaultDeepenRatio = 2f;
 
    }

    [Test]
    public void CheckGenerateNoiseMapMinimal(){
        // Arrange

        // Act

        // Assert
        CheckGenerateNoiseMap(
            minimalNoiseSettings, 
            dontDeepenSea, 
            defaultDeepenRatio);
    }

    [Test]
    public void CheckGenerateNoiseMapTexture(){
        // Arrange

        // Act

        // Assert
        CheckGenerateNoiseMap(
            textureNoiseSettings, 
            dontDeepenSea, 
            defaultDeepenRatio);
    }

    [Test]
    public void CheckGenerateNoiseMapIsland(){
        // Arrange

        // Act

        // Assert
        CheckGenerateNoiseMap(
            islandNoiseSettings, 
            dontDeepenSea, 
            defaultDeepenRatio);
    }

    [Test]
    public void CheckGenerateNoiseMapIslandPlus(){
        // Arrange

        // Act

        // Assert
        CheckGenerateNoiseMap(
            islandNoiseSettings, 
            doDeepenSea, 
            defaultDeepenRatio);
    }

    public void CheckGenerateNoiseMap(NoiseSettings noiseSettings, bool deepenSea, float deepenRatio){
        // Act
        float[,] actual = Noise.GenerateNoiseMap(
            defaultMapWidth, 
            defaultMapHeight,
            noiseSettings, 
            defaultSampleCentre, 
            deepenSea, 
            deepenRatio);

        // Assert
        float maxNoiseHeight = float.MinValue;
		float minNoiseHeight = float.MaxValue;
		for (int y = 0; y < deafultSize; y++) {
			for (int x = 0; x < deafultSize; x++) {
                float height = actual[x, y];
				if (height > maxNoiseHeight) {
					maxNoiseHeight = height;
				} 
				if (height < minNoiseHeight) {
					minNoiseHeight = height;
				}
            }
        }
        Debug.LogFormat("Min: {0}, Max: {1}", minNoiseHeight, maxNoiseHeight);
        Assert.GreaterOrEqual(
            minNoiseHeight, minimalMinHeight, 
            "Min Height {0} should be greater than minimal min height {1}", 
            minNoiseHeight, minimalMinHeight);
        Assert.LessOrEqual(
            maxNoiseHeight, minimalMaxHeight, 
            "Max Height {0} should be less than minimal max height {1}", 
            maxNoiseHeight, minimalMaxHeight);
        Assert.Less(
            minNoiseHeight, minimalMaxHeight, 
            "Min Height {0} should be less than minimal max height {1}", 
            minNoiseHeight, minimalMaxHeight);
        Assert.Greater(
            maxNoiseHeight, minimalMinHeight, 
            "Max Height {0} should be greater than minimal min height {1}", 
            maxNoiseHeight, minimalMinHeight);
    }
}
